## configuration

# Site
title:                           잠만보의 개발 블로그
subtitle:                        잠만보가 알려주는 개발 이야기
author:                          Mambo
description:
language:                        ko
timezone:                        UTC

# URL
url:                             https://kdevkr.github.io
root:                            /
permalink:                       :title/
permalink_defaults:

# Directory
source_dir:                      source
public_dir:                      public
archive_dir:                     archives
category_dir:                    categories
i18n_dir:                        :lang
tag_dir:                         tags
skip_render:                     [README.md, draft/**]

# Writing
default_layout:                  post
render_drafts:                   false
titlecase:                       true
external_link:                   true
post_asset_folder:               true
future:                          false

# Category & Tag
default_category:                uncategorized
category_map:
tag_map:

# Date / Time format
date_format:                     YYYY-MM-DD
time_format:                     HH:mm:ss

# Pagination
per_page:                        10
pagination_dir:                  page

deploy:
  type:                          git
  repo:                          https://__GITHUB_TOKEN__@github.com/kdevkr/kdevkr.github.io.git
  branch:                        master

google_site_verification:        googled619795c447b2a1d
naver_site_verification:         967670e7891eb52e115709ce4890e2e8f576a1e5

article_emoji:
  full:                          true

browsersync:
  ui:                            false

# https://futurecreator.github.io/2016/06/23/search-engine-optimization-hexo-plugins/
nofollow:
  enable:                        true

sitemap:
  path:                          sitemap.xml
  tag:                           false
  category:                      false

markdown: 'default'

highlight:
    enable: true
    line_number: false
    wrap: true
    hljs: false

index_generator:
  path:                      ''
  per_page:                  10
  order_by:                  -date

category_generator:
  per_page:                  10

archive_generator:
  enabled:                   false
  per_page:                  10
  yearly:                    true
  monthly:                   true
  daily:                     true
  order_by:                  -date

tag_generator:
  per_page: 10
  order_by: -date

theme: next
theme_config:
  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------
  menu:
    home: / || fas fa-home
    archives: /archives/ || fas fa-archive
    Spring: /spring || fas fa-seedling
    Vue.js: /vuejs || fab fa-vuejs
      # 파이썬: /python || fab fa-python
    PostgreSQL: /database/postgresql || fas fa-database
    KDB+: /database/kdb || fas fa-database
    데브 옵스:
      default: /dev-ops/ || fab fa-connectdevelop
      Jenkins: /jenkins || fab fa-jenkins
      Docker: /docker || fab fa-docker
      kubernetes: /kubernetes || fas fa-dharmachakra
    꾸르팁:
      default: /tips/ || far fa-grin-tongue-wink
      터미널: /shell/ || fas fa-desktop
    소개: /about/ || fas fa-user
